#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# # login JWT
# api_login_check:
#     path: /api/login_check

app_logout_admin:
    path: /admin/logout

not_found:
    path: '{any}'
    controller: App\Controller\BackOffice\CardController::error404Action
    requirements:
        any: .+